### ISSUE TITLE
error: 'struct i2s_pin_config_t' has no member named 'mck_io_num'

### ISSUE THREAD

**Issue by nica-f** [pschatzmann/arduino-audiokit#25]
Current 'master' does not compile using Arduino 1.8.15 and ESP32 Arduino SDK from the 1.0.x series within Arduino (currently tested with 1.0.6).

**Comment by pschatzmann** [comment]
I just committed a correction. 
However I recommend to use the latest version

**Comment by nica-f** [comment]
Tadah!
Now it builds again, thank you!

And yes, I will need to check out the 2.x series, I am just afraid that other projects may break with this major update...

**Comment by pschatzmann** [comment]
ps. I suggest that you have a look at https://github.com/pschatzmann/arduino-audio-tools.
It has plenty of examples how to decode from URL streams
